#!/bin/bash
echo "------------ Running post push hook ------------"
echo "---- Setting up authentication ----"
mkdir .gcloud-secrets
echo "$GCLOUD_AUTH" >> .gcloud-secrets/gcloud_auth.json
export GOOGLE_APPLICATION_CREDENTIALS=.gcloud-secrets/gcloud_auth.json

echo "---- Setting up gcloud and kubectl ----"
export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-get update && sudo apt-get install google-cloud-sdk

sudo apt-get update && sudo apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo touch /etc/apt/sources.list.d/kubernetes.list
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubectl

echo "---- Deploying image to kubernetes cluster ----"
gcloud container clusters get-credentials soundplace --zone us-central1-b --project soundplace-infra
kubectl rolling-update data-api-pod --image=tsirlucas/soundplace-api:latest --image-pull-policy=Always
